name: compile-macosx-plugin
on:
  push:
    branches: [ main ]
    paths:
      - 'src/plugin'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/plugin'
  workflow_dispatch:
jobs:
  buildos:
    name: Compile MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone OSQP
        uses: actions/checkout@main
        with:
          repository: osqp/osqp
          path: './osqp'
          submodules: recursive
      - name: Clone ECOS
        uses: actions/checkout@main
        with:
          repository: embotech/ecos
          path: './ecos'
          submodules: recursive
      - name: compile x86_64
        run: |
          RUN_CLONE=0 RUN_OS=APPLE_X86_64 RUN_COPY=0 bash src/compile.sh
          shasum src/build/honestosqp_macosx86_64.plugin
          shasum src/build/honestecos_macosx86_64.plugin
          otool -L src/build/honestosqp_macosx86_64.plugin
          otool -L src/build/honestecos_macosx86_64.plugin
      - name: compile arm64
        run: |
          RUN_CLONE=0 RUN_OS=APPLE_ARM64 RUN_COPY=0 bash src/compile.sh
          shasum src/build/honestosqp_macosxarm64.plugin
          shasum src/build/honestecos_macosxarm64.plugin
          otool -L src/build/honestosqp_macosxarm64.plugin
          otool -L src/build/honestecos_macosxarm64.plugin
      - name: combine plugins
        run: |
          rm -f src/build/honestosqp_macosx.plugin
          rm -f src/build/honestecos_macosx.plugin
          lipo -create -output src/build/honestosqp_macosx.plugin src/build/honestosqp_macosx86_64.plugin src/build/honestosqp_macosxarm64.plugin
          lipo -create -output src/build/honestecos_macosx.plugin src/build/honestecos_macosx86_64.plugin src/build/honestecos_macosxarm64.plugin
          shasum src/build/honestosqp_macosx.plugin
          shasum src/build/honestecos_macosx.plugin
          otool -L src/build/honestosqp_macosx.plugin
          otool -L src/build/honestecos_macosx.plugin
      - name: commit plugin
        run: |
          git config --global user.name "{{ github.COMMITTER_EMAIL }}"
          git config --global user.email "{{ github.COMMITTER_EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -f src/build/honestosqp_macosx*.plugin
          git add -f src/build/honestecos_macosx*.plugin
          echo ${GITHUB_REF##*/}
          [ -n "$(git status --porcelain)" ] && git commit -m "[Automated Commit] OSX plugin"
          git fetch
          git push -f origin HEAD:${GITHUB_REF##*/}
  buildlinux:
    name: Compile Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Linux
        run: |
          bash src/compile.sh
      - name: commit plugin
        run: |
          git config --global user.name "{{ github.actor }}"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -f src/build/honestosqp_unix.plugin
          git add -f src/build/honestecos_unix.plugin
          echo ${GITHUB_REF##*/}
          [ -n "$(git status --porcelain)" ] && git commit -m "[Automated Commit] Linux plugin"
          git fetch
          git push -f origin HEAD:${GITHUB_REF##*/}
